DotnetEfCore/dotnet-ef-core6/Models/ErrorViewModel.cs
namespace dotnet_ef_core6.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DotnetEfCore/dotnet-ef-core6/Controllers/AssetController.cs
using dotnet_ef_core6.DataContext;
using Microsoft.AspNetCore.Mvc;

namespace dotnet_ef_core6.Controllers
{
    public class AssetController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AssetController (ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<AssetEntity> assets = _context.AssetEntities.ToList();
            return View(assets);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            AssetEntity asset = _context.AssetEntities.Find(id);
            return View(asset);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("NoAsset, AssetName, AssetType, PurchaseYear")] AssetEntity request)
        {
            // tambah ke entity
            _context.AssetEntities.Add(request);
            // commit ke database
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var entity = _context.AssetEntities.Find(id);
            return View(entity);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var entity = _context.AssetEntities.Find(id);
            //if (entity == null)
            //{
            //    return Redirect("GetAll");
            //}
            // buang dari entity
            _context.AssetEntities.Remove(entity);
            // commiting to database
            _context.SaveChanges();
            return View(entity);
        }

        [HttpPost]
        public IActionResult Update([Bind("Id, NoAsset, AssetName, AssetType, PurchaseYear")] AssetEntity request)
        {
            //update ke entity
            _context.AssetEntities.Update(request);
            //add to database
            _context.SaveChanges();
            return Redirect("GetAll");
        }
    }
}

DotnetEfCore/dotnet-ef-core6/Controllers/AuditController.cs
using dotnet_ef_core6.DataContext;
using Microsoft.AspNetCore.Mvc;

namespace dotnet_ef_core6.Controllers
{
    public class AuditController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AuditController (ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<AuditEntity> audits = _context.AuditEntities.ToList();
            return View(audits);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            AuditEntity audit = _context.AuditEntities.Find(id);
            return View(audit);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("NoAsset, AssetName, SerialNo, PIC, TypeWindows")] AuditEntity request)
        {
            // tambah ke entity
            _context.AuditEntities.Add(request);
            // commit ke database
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var entity = _context.AuditEntities.Find(id);
            return View(entity);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var entity = _context.AuditEntities.Find(id);
            //if (entity == null)
            //{
            //    return Redirect("GetAll");
            //}
            // buang dari entity
            _context.AuditEntities.Remove(entity);
            // commiting to database
            _context.SaveChanges();
            return View(entity);
        }

        [HttpPost]
        public IActionResult Update([Bind("Id, NoAsset, AssetName, SerialNo, PIC, TypeWindows")] AuditEntity request)
        {
            //update ke entity
            _context.AuditEntities.Update(request);
            //add to database
            _context.SaveChanges();
            return Redirect("GetAll");
        }
    }
}

DotnetEfCore/dotnet-ef-core6/Controllers/CategoryController.cs
using dotnet_ef_core6.DataContext;
using Microsoft.AspNetCore.Mvc;

namespace dotnet_ef_core6.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<CategoryEntity> categories = _context.CategoryEntities.ToList();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            CategoryEntity category = _context.CategoryEntities.Find(id);
            return View(category);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("CategoryCode, CategoryName, Description")] CategoryEntity request)
        {
            // tambah ke entity
            _context.CategoryEntities.Add(request);
            // commit ke database
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var entity = _context.CategoryEntities.Find(id);
            return View(entity);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var entity = _context.CategoryEntities.Find(id);
            //if (entity == null)
            //{
            //    return Redirect("GetAll");
            //}
            // buang dari entity
            _context.CategoryEntities.Remove(entity);
            // commiting to database
            _context.SaveChanges();
            return View(entity);
        }

        [HttpPost]
        public IActionResult Update([Bind("Id, CategoryCode, CategoryName, Description")] CategoryEntity request)
        {
            //update ke entity
            _context.CategoryEntities.Update(request);
            //add to database
            _context.SaveChanges();
            return Redirect("GetAll");
        }
    }
}

DotnetEfCore/dotnet-ef-core6/Controllers/HomeController.cs
using dotnet_ef_core6.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace dotnet_ef_core6.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DotnetEfCore/dotnet-ef-core6/Views/Asset/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model dotnet_ef_core6.DataContext.AssetEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Add Asset</h2>
<form asp-action="Save" asp-controller="Asset" method="post">
    <div class="form-group">
        <label asp-for="NoAsset"></label>
        <input asp-for="NoAsset" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AssetName"></label>
        <input asp-for="AssetName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AssetType"></label>
        <input asp-for="AssetType" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PurchaseYear"></label>
        <input asp-for="PurchaseYear" class="form-control" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>

</form>

DotnetEfCore/dotnet-ef-core6/Views/Asset/Delete.cshtml
@model dotnet_ef_core6.DataContext.AssetEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}
<h2>Delete</h2>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to delete this?</h3>
<form asp-action="GetAll" method="get">
    <button type="submit" class="btn btn-primary">Yes</button>
</form>

DotnetEfCore/dotnet-ef-core6/Views/Asset/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model dotnet_ef_core6.DataContext.AssetEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Details</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>No Asset</th>
        <td>@Model.NoAsset</td>
    </tr>
    <tr>
        <th>Asset Name</th>
        <td>@Model.AssetName</td>
    </tr>
    <tr>
        <th>Asset Type</th>
        <td>@Model.AssetType</td>
    </tr>
    <tr>
        <th>Purchase Year</th>
        <td>@Model.PurchaseYear</td>
    </tr>

</table>

DotnetEfCore/dotnet-ef-core6/Views/Asset/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model dotnet_ef_core6.DataContext.AssetEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Edit Asset</h2>
<form asp-action="Update" asp-controller="Asset" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="NoAsset"></label>
        <input asp-for="NoAsset" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AssetName"></label>
        <input asp-for="AssetName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AssetType"></label>
        <input asp-for="AssetType" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PurchaseYear"></label>
        <input asp-for="PurchaseYear" class="form-control" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>

</form>

DotnetEfCore/dotnet-ef-core6/Views/Asset/GetAll.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<dotnet_ef_core6.DataContext.AssetEntity>
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>All Asset</h2>
<table class="table table-responsive">
    <thead>
    <tr>
        <th>ID</th>
        <th>No Asset</th>
        <th>Asset Name</th>
        <th>Asset Type</th>
        <th>Purchase Year</th>
        <th>Action</th>
    </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.NoAsset</td>
                <td>@item.AssetName</td>
                <td>@item.AssetType</td>
                <td>@item.PurchaseYear</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Add" class="btn btn-primary">Add</a>

DotnetEfCore/dotnet-ef-core6/Views/Audit/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model dotnet_ef_core6.DataContext.AuditEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Add Asset</h2>
<form asp-action="Save" asp-controller="Audit" method="post">
    <div class="form-group">
        <label asp-for="NoAsset"></label>
        <input asp-for="NoAsset" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AssetName"></label>
        <input asp-for="AssetName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="SerialNo"></label>
        <input asp-for="SerialNo" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PIC"></label>
        <input asp-for="PIC" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="TypeWindows"></label>
        <input asp-for="TypeWindows" class="form-control" />
    </div>

    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>

</form>

DotnetEfCore/dotnet-ef-core6/Views/Audit/Delete.cshtml
@model dotnet_ef_core6.DataContext.AuditEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}
<h2>Delete</h2>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to delete this?</h3>
<form asp-action="GetAll" method="get">
    <button type="submit" class="btn btn-primary">Yes</button>
</form>

DotnetEfCore/dotnet-ef-core6/Views/Audit/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model dotnet_ef_core6.DataContext.AuditEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Details</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>No Asset</th>
        <td>@Model.NoAsset</td>
    </tr>
    <tr>
        <th>Asset Name</th>
        <td>@Model.AssetName</td>
    </tr>
    <tr>
        <th>Asset Type</th>
        <td>@Model.SerialNo</td>
    </tr>
    <tr>
        <th>Purchase Year</th>
        <td>@Model.PIC</td>
    </tr>
    <tr>
        <th>Type Windows</th>
        <td>@Model.TypeWindows</td>
    </tr>

</table>

DotnetEfCore/dotnet-ef-core6/Views/Audit/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model dotnet_ef_core6.DataContext.AuditEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Edit Audit</h2>
<form asp-action="Update" asp-controller="Audit" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="NoAsset"></label>
        <input asp-for="NoAsset" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AssetName"></label>
        <input asp-for="AssetName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="SerialNo"></label>
        <input asp-for="SerialNo" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PIC"></label>
        <input asp-for="PIC" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="TypeWindows"></label>
        <input asp-for="TypeWindows" class="form-control" />
    </div>

    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>

</form>

DotnetEfCore/dotnet-ef-core6/Views/Audit/GetAll.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<dotnet_ef_core6.DataContext.AuditEntity>
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>All Audit</h2>
<table class="table table-responsive">
    <thead>
    <tr>
        <th>ID</th>
        <th>No Asset</th>
        <th>Asset Name</th>
        <th>Serial No</th>
        <th>PIC</th>
        <th>Type Windows</th>
        <th>Action</th>
    </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.NoAsset</td>
                <td>@item.AssetName</td>
                <td>@item.SerialNo</td>
                <td>@item.PIC</td>
                <td>@item.TypeWindows</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Add" class="btn btn-primary">Add</a>

DotnetEfCore/dotnet-ef-core6/Views/Category/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model dotnet_ef_core6.DataContext.CategoryEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Add Category</h2>
<form asp-action="Save" asp-controller="Category" method="post">
    <div class="form-group">
        <label asp-for="CategoryCode"></label>
        <input asp-for="CategoryCode" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="CategoryName"></label>
        <input asp-for="CategoryName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>

</form>

DotnetEfCore/dotnet-ef-core6/Views/Category/Delete.cshtml
@model dotnet_ef_core6.DataContext.CategoryEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}
<h2>Delete</h2>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to delete this?</h3>
<form asp-action="GetAll" method="get">
    <button type="submit" class="btn btn-primary">Yes</button>
</form>

DotnetEfCore/dotnet-ef-core6/Views/Category/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model dotnet_ef_core6.DataContext.CategoryEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Details</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Category Code</th>
        <td>@Model.CategoryCode</td>
    </tr>
    <tr>
        <th>Category Name</th>
        <td>@Model.CategoryName</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>@Model.Description</td>
    </tr>

</table>

DotnetEfCore/dotnet-ef-core6/Views/Category/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model dotnet_ef_core6.DataContext.CategoryEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Edit Category</h2>
<form asp-action="Update" asp-controller="Category" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="CategoryCode"></label>
        <input asp-for="CategoryCode" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="CategoryName"></label>
        <input asp-for="CategoryName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>

</form>

DotnetEfCore/dotnet-ef-core6/Views/Category/GetAll.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<dotnet_ef_core6.DataContext.CategoryEntity>
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>All Category</h2>
<table class="table table-responsive">
    <thead>
    <tr>
        <th>ID</th>
        <th>Category Code</th>
        <th>Category Name</th>
        <th>Description</th>
        <th>Action</th>
    </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.CategoryCode</td>
                <td>@item.CategoryName</td>
                <td>@item.Description</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Add" class="btn btn-primary">Add</a>

DotnetEfCore/dotnet-ef-core6/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DotnetEfCore/dotnet-ef-core6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dotnet_ef_core6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/dotnet_ef_core6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">dotnet_ef_core6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="GetAll">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asset" asp-action="GetAll">Asset</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Audit" asp-action="GetAll">Audit</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - dotnet_ef_core6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>